version: '3.8'

services:
  backend:
    build: ./backend
    container_name: cc-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: cc-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend